api_platform:
    resource: .
    type: api_platform
    prefix: /api

api_get_image:
    path: '/api/image/map/{id}'
    methods:  ['GET']
    defaults:
        _controller: App\Controller\ImageController:retrieveImageFile
        _api_resource_class: 'App\Entity\Mappa'
        _api_collection_operation_name: 'retrieve_map_image'
api_insert_image:
    path: '/api/image/map/{id}'
    methods:  ['POST']
    defaults:
        _controller: App\Controller\ImageController:createMappaImageFile
        _api_resource_class: 'App\Entity\Mappa'
        _api_collection_operation_name: 'post_map_image'
api_update_image:
    path: '/api/image/map/{id}'
    methods:  ['PUT']
    defaults:
        _controller: App\Controller\ImageController:updateMappaImage
        _api_resource_class: 'App\Entity\Mappa'
        _api_collection_operation_name: 'update_img'
api_delete_map_data:
    path: '/api/custom/mappas/{id}'
    methods:  ['DELETE']
    defaults:
        _controller: App\Controller\MappaController:delete
        _api_resource_class: 'App\Entity\Mappa'
        _api_collection_operation_name: 'delete_dati_mappa'